const audience =[
  {
    "uuid": "94272f2d-f701-4adb-b164-1e6a9a03440f",
    "clientUuid": "927f668a-4479-433d-82b9-b23975f0d737",
    "title": "Entreprises manufacturières",
    "description": "Les entreprises manufacturières utilisent des équipements de sablage pour nettoyer et préparer des surfaces métalliques avant des opérations de peinture ou de traitement de surface, garantissant la durabilité et la qualité des produits finis.",
    "subIndustryId": 20102010,
    "countryId": 11,
    "stateId": 3651,
    "cityId": 873,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1733927448780,
    "subIndustryName": "Building Products",
    "subIndustryDescription": "Manufacturers of building components and home improvement products and equipment. Excludes lumber and plywood classified under Forest Products and cement and other materials classified in the Construction Materials Sub-Industry.",
    "industryId": 201020,
    "industryName": "Building Products",
    "industryGroupId": 2010,
    "industryGroupName": "Capital Goods",
    "sectorId": 20,
    "sectorName": "Industrials",
    "countryName": "Argentina",
    "stateName": "Chubut",
    "cityName": "Departamento de Cushamen",
    "pageCount": 14
  },
  {
    "uuid": "133756b3-3773-4afd-b7d4-f7d71c5568e3",
    "clientUuid": "927f668a-4479-433d-82b9-b23975f0d737",
    "title": "Precision Component Manufacturers",
    "description": "Companies producing small, delicate automotive parts such as fuel injectors and valve components, requiring glass bead blasting for gentle cleaning and surface finishing.",
    "subIndustryId": 25101010,
    "countryId": 39,
    "stateId": 873,
    "cityId": 16709,
    "revenue": "25000000-50000000",
    "image": null,
    "score": null,
    "createdAt": 1734215291329,
    "subIndustryName": "Automotive Parts & Equipment",
    "subIndustryDescription": "Manufacturers of parts and accessories for  automobiles and motorcycles. Excludes companies classified in the Tires & Rubber Sub-Industry.",
    "industryId": 251010,
    "industryName": "Automobile Components",
    "industryGroupId": 2510,
    "industryGroupName": "Automobiles & Components",
    "sectorId": 25,
    "sectorName": "Consumer Discretionary",
    "countryName": "Canada",
    "stateName": "Quebec",
    "cityName": "Montréal",
    "pageCount": 3
  },
  {
    "uuid": "495b2c56-45e6-471c-8a6d-347876582c77",
    "clientUuid": "927f668a-4479-433d-82b9-b23975f0d737",
    "title": "Aftermarket Accessory Manufacturers",
    "description": "Manufacturers of aftermarket automotive parts like rims, spoilers, and trim pieces, utilizing polishing compounds to ensure premium-quality finishes.",
    "subIndustryId": 25101010,
    "countryId": 39,
    "stateId": 875,
    "cityId": 17145,
    "revenue": "25000000-50000000",
    "image": null,
    "score": null,
    "createdAt": 1734215291394,
    "subIndustryName": "Automotive Parts & Equipment",
    "subIndustryDescription": "Manufacturers of parts and accessories for  automobiles and motorcycles. Excludes companies classified in the Tires & Rubber Sub-Industry.",
    "industryId": 251010,
    "industryName": "Automobile Components",
    "industryGroupId": 2510,
    "industryGroupName": "Automobiles & Components",
    "sectorId": 25,
    "sectorName": "Consumer Discretionary",
    "countryName": "Canada",
    "stateName": "British Columbia",
    "cityName": "Vancouver",
    "pageCount": 3
  },
  {
    "uuid": "96c5014e-b600-4901-80df-7cd7eb170a31",
    "clientUuid": "927f668a-4479-433d-82b9-b23975f0d737",
    "title": "Precast Concrete Manufacturers",
    "description": "Companies producing precast concrete elements such as beams, panels, and decorative structures, utilizing vibratory media for smoothing and deburring edges.",
    "subIndustryId": 15102010,
    "countryId": 233,
    "stateId": 1416,
    "cityId": 120784,
    "revenue": "50000000-100000000",
    "image": null,
    "score": null,
    "createdAt": 1734215291130,
    "subIndustryName": "Construction Materials",
    "subIndustryDescription": "Manufacturers of construction materials including sand, clay, gypsum, lime, aggregates, cement, concrete and bricks. Other finished or semi-finished building materials are classified  in the Building Products Sub-Industry.",
    "industryId": 151020,
    "industryName": "Construction Materials",
    "industryGroupId": 1510,
    "industryGroupName": "Materials",
    "sectorId": 15,
    "sectorName": "Materials",
    "countryName": "United States",
    "stateName": "California",
    "cityName": "Los Angeles",
    "pageCount": 3
  },
  {
    "uuid": "c4f7177e-9ff9-4894-9014-5851c81368d9",
    "clientUuid": "927f668a-4479-433d-82b9-b23975f0d737",
    "title": "Tile and Decorative Stone Producers",
    "description": "Manufacturers of tiles and stone products for construction projects, requiring vibratory media to ensure uniform and smooth finishes.",
    "subIndustryId": 15102010,
    "countryId": 233,
    "stateId": 1436,
    "cityId": 123562,
    "revenue": "100000000+",
    "image": null,
    "score": null,
    "createdAt": 1734215291232,
    "subIndustryName": "Construction Materials",
    "subIndustryDescription": "Manufacturers of construction materials including sand, clay, gypsum, lime, aggregates, cement, concrete and bricks. Other finished or semi-finished building materials are classified  in the Building Products Sub-Industry.",
    "industryId": 151020,
    "industryName": "Construction Materials",
    "industryGroupId": 1510,
    "industryGroupName": "Materials",
    "sectorId": 15,
    "sectorName": "Materials",
    "countryName": "United States",
    "stateName": "Florida",
    "cityName": "Orlando",
    "pageCount": 3
  },
  {
    "uuid": "d4c50bb4-b919-4c7b-9b0a-b3dfde4eb2df",
    "clientUuid": "927f668a-4479-433d-82b9-b23975f0d737",
    "title": "Engine Component Manufacturers",
    "description": "Companies producing engine components for aircraft, using solvent-based cleaners to remove grease and contaminants during production.",
    "subIndustryId": 20101010,
    "countryId": 233,
    "stateId": 1462,
    "cityId": 126104,
    "revenue": "100000000+",
    "image": null,
    "score": null,
    "createdAt": 1734215291076,
    "subIndustryName": "Aerospace & Defense",
    "subIndustryDescription": "Manufacturers of civil or military aerospace and defense equipment, parts or products. Includes defense electronics and space equipment.",
    "industryId": 201010,
    "industryName": "Aerospace & Defense",
    "industryGroupId": 2010,
    "industryGroupName": "Capital Goods",
    "sectorId": 20,
    "sectorName": "Industrials",
    "countryName": "United States",
    "stateName": "Washington",
    "cityName": "Seattle",
    "pageCount": 3
  },
  {
    "uuid": "156dd957-d1ef-4c00-ad3b-b211876a48d2",
    "clientUuid": "927f668a-4479-433d-82b9-b23975f0d737",
    "title": "Automotive Body Part Manufacturers",
    "description": "Companies producing automotive body panels, frames, and other structural components, relying on powder coating equipment for durable and high-quality finishes.",
    "subIndustryId": 25101010,
    "countryId": 233,
    "stateId": 4851,
    "cityId": 141223,
    "revenue": "50000000-100000000",
    "image": null,
    "score": null,
    "createdAt": 1734215291381,
    "subIndustryName": "Automotive Parts & Equipment",
    "subIndustryDescription": "Manufacturers of parts and accessories for  automobiles and motorcycles. Excludes companies classified in the Tires & Rubber Sub-Industry.",
    "industryId": 251010,
    "industryName": "Automobile Components",
    "industryGroupId": 2510,
    "industryGroupName": "Automobiles & Components",
    "sectorId": 25,
    "sectorName": "Consumer Discretionary",
    "countryName": "United States",
    "stateName": "Ohio",
    "cityName": "Cleveland",
    "pageCount": 3
  },
  {
    "uuid": "af067e24-ee14-4380-be62-f886aca58112",
    "clientUuid": "927f668a-4479-433d-82b9-b23975f0d737",
    "title": "Structural Steel Manufacturers",
    "description": "Companies specializing in producing steel beams and structures for construction, relying on steel grit for surface preparation and rust removal.",
    "subIndustryId": 15102010,
    "countryId": 39,
    "stateId": 866,
    "cityId": 17121,
    "revenue": "100000000+",
    "image": null,
    "score": null,
    "createdAt": 1734215291280,
    "subIndustryName": "Construction Materials",
    "subIndustryDescription": "Manufacturers of construction materials including sand, clay, gypsum, lime, aggregates, cement, concrete and bricks. Other finished or semi-finished building materials are classified  in the Building Products Sub-Industry.",
    "industryId": 151020,
    "industryName": "Construction Materials",
    "industryGroupId": 1510,
    "industryGroupName": "Materials",
    "sectorId": 15,
    "sectorName": "Materials",
    "countryName": "Canada",
    "stateName": "Ontario",
    "cityName": "Toronto",
    "pageCount": 0
  },
  {
    "uuid": "f2a8593e-3451-4b9a-a2db-d9900f90cfc1",
    "clientUuid": "927f668a-4479-433d-82b9-b23975f0d737",
    "title": "Valve and Equipment Manufacturers",
    "description": "Companies producing precision components like valves and pumps for oil and gas operations, requiring robust surface treatment for durability.",
    "subIndustryId": 10101020,
    "countryId": 39,
    "stateId": 872,
    "cityId": 16396,
    "revenue": "100000000+",
    "image": null,
    "score": null,
    "createdAt": 1734215290788,
    "subIndustryName": "Oil & Gas Equipment & Services",
    "subIndustryDescription": "Manufacturers of equipment, including drilling rigs and equipment, and providers of supplies and services to companies involved in the drilling, evaluation and completion of oil and gas wells.",
    "industryId": 101010,
    "industryName": "Energy Equipment & Services",
    "industryGroupId": 1010,
    "industryGroupName": "Energy",
    "sectorId": 10,
    "sectorName": "Energy",
    "countryName": "Canada",
    "stateName": "Alberta",
    "cityName": "Edmonton",
    "pageCount": 0
  },
  {
    "uuid": "6f841924-d8de-42f7-8e0e-788c6dc491ce",
    "clientUuid": "927f668a-4479-433d-82b9-b23975f0d737",
    "title": "Entreprises manufacturières",
    "description": "Les entreprises manufacturières utilisent des équipements de sablage pour nettoyer et préparer des surfaces métalliques avant des opérations de peinture ou de traitement de surface, garantissant la durabilité et la qualité des produits finis.",
    "subIndustryId": 20102010,
    "countryId": 11,
    "stateId": 3651,
    "cityId": 873,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1733927450530,
    "subIndustryName": "Building Products",
    "subIndustryDescription": "Manufacturers of building components and home improvement products and equipment. Excludes lumber and plywood classified under Forest Products and cement and other materials classified in the Construction Materials Sub-Industry.",
    "industryId": 201020,
    "industryName": "Building Products",
    "industryGroupId": 2010,
    "industryGroupName": "Capital Goods",
    "sectorId": 20,
    "sectorName": "Industrials",
    "countryName": "Argentina",
    "stateName": "Chubut",
    "cityName": "Departamento de Cushamen",
    "pageCount": 0
  },
  {
    "uuid": "4c1b56e8-c85b-4f6e-b278-bc92a69ee809",
    "clientUuid": "927f668a-4479-433d-82b9-b23975f0d737",
    "title": "Entreprises manufacturières",
    "description": "Les entreprises manufacturières utilisent des équipements de sablage pour nettoyer et préparer des surfaces métalliques avant des opérations de peinture ou de traitement de surface, garantissant la durabilité et la qualité des produits finis.",
    "subIndustryId": 20102010,
    "countryId": 11,
    "stateId": 3651,
    "cityId": 873,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1733927450789,
    "subIndustryName": "Building Products",
    "subIndustryDescription": "Manufacturers of building components and home improvement products and equipment. Excludes lumber and plywood classified under Forest Products and cement and other materials classified in the Construction Materials Sub-Industry.",
    "industryId": 201020,
    "industryName": "Building Products",
    "industryGroupId": 2010,
    "industryGroupName": "Capital Goods",
    "sectorId": 20,
    "sectorName": "Industrials",
    "countryName": "Argentina",
    "stateName": "Chubut",
    "cityName": "Departamento de Cushamen",
    "pageCount": 0
  },
  {
    "uuid": "7ee28466-6cbb-4727-aa55-1f58bf144315",
    "clientUuid": "927f668a-4479-433d-82b9-b23975f0d737",
    "title": "Heavy-Duty Construction Equipment Manufacturers",
    "description": "Producers of construction machinery like excavators and cranes, using steel grit for cleaning and preparing metal surfaces before coating or assembly.",
    "subIndustryId": 15102010,
    "countryId": 233,
    "stateId": 1425,
    "cityId": 113931,
    "revenue": "100000000+",
    "image": null,
    "score": null,
    "createdAt": 1734215291178,
    "subIndustryName": "Construction Materials",
    "subIndustryDescription": "Manufacturers of construction materials including sand, clay, gypsum, lime, aggregates, cement, concrete and bricks. Other finished or semi-finished building materials are classified  in the Building Products Sub-Industry.",
    "industryId": 151020,
    "industryName": "Construction Materials",
    "industryGroupId": 1510,
    "industryGroupName": "Materials",
    "sectorId": 15,
    "sectorName": "Materials",
    "countryName": "United States",
    "stateName": "Illinois",
    "cityName": "Chicago",
    "pageCount": 0
  }
]
export default audience