const audience =[
  {
    "uuid": "132e4c7e-d02b-432f-bd25-bfe97b8adc42",
    "clientUuid": "feec8a1b-7498-4d2e-af12-46389ae9a095",
    "title": "Ébénistes",
    "description": "Ébénistes au Québec, Canada, qui achètent des panneaux décoratifs pour fabriquer des meubles sur mesure, en choisissant parmi une vaste sélection de matériaux de qualité pour satisfaire les exigences esthétiques et fonctionnelles de leurs clients.",
    "subIndustryId": 15105010,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1733763642011,
    "subIndustryName": "Forest Products",
    "subIndustryDescription": "Manufacturers of timber and related wood products. Includes lumber for the building industry.",
    "industryId": 151050,
    "industryName": "Paper & Forest Products",
    "industryGroupId": 1510,
    "industryGroupName": "Materials",
    "sectorId": 15,
    "sectorName": "Materials",
    "pageCount": 12
  },
  {
    "uuid": "e6224001-4d96-45e2-91e7-8076c521703a",
    "clientUuid": "feec8a1b-7498-4d2e-af12-46389ae9a095",
    "title": "Interior Designers",
    "description": "Professionals focusing on aesthetic and functional design, seeking high-quality decorative panels to enhance their projects and meet client expectations.",
    "subIndustryId": 15102010,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1734630465620,
    "subIndustryName": "Construction Materials",
    "subIndustryDescription": "Manufacturers of construction materials including sand, clay, gypsum, lime, aggregates, cement, concrete and bricks. Other finished or semi-finished building materials are classified  in the Building Products Sub-Industry.",
    "industryId": 151020,
    "industryName": "Construction Materials",
    "industryGroupId": 1510,
    "industryGroupName": "Materials",
    "sectorId": 15,
    "sectorName": "Materials",
    "pageCount": 4
  },
  {
    "uuid": "9f3de58d-c2c9-4024-965c-0900b0f721ec",
    "clientUuid": "feec8a1b-7498-4d2e-af12-46389ae9a095",
    "title": "Contractors",
    "description": "Building contractors looking for reliable suppliers of decorative and construction materials to complete residential and commercial projects.",
    "subIndustryId": 15102010,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1734630524745,
    "subIndustryName": "Construction Materials",
    "subIndustryDescription": "Manufacturers of construction materials including sand, clay, gypsum, lime, aggregates, cement, concrete and bricks. Other finished or semi-finished building materials are classified  in the Building Products Sub-Industry.",
    "industryId": 151020,
    "industryName": "Construction Materials",
    "industryGroupId": 1510,
    "industryGroupName": "Materials",
    "sectorId": 15,
    "sectorName": "Materials",
    "pageCount": 0
  },
  {
    "uuid": "c59624a1-1c77-4cce-9adf-40d62084a94f",
    "clientUuid": "feec8a1b-7498-4d2e-af12-46389ae9a095",
    "title": "Architects",
    "description": "Architectural professionals requiring durable and aesthetically attractive finishing materials for their designs, including solid and decorative panels.",
    "subIndustryId": 15102010,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1734630591479,
    "subIndustryName": "Construction Materials",
    "subIndustryDescription": "Manufacturers of construction materials including sand, clay, gypsum, lime, aggregates, cement, concrete and bricks. Other finished or semi-finished building materials are classified  in the Building Products Sub-Industry.",
    "industryId": 151020,
    "industryName": "Construction Materials",
    "industryGroupId": 1510,
    "industryGroupName": "Materials",
    "sectorId": 15,
    "sectorName": "Materials",
    "pageCount": 0
  },
  {
    "uuid": "d9f697d8-7609-4c80-96a8-e2df20b9d1f9",
    "clientUuid": "feec8a1b-7498-4d2e-af12-46389ae9a095",
    "title": "Furniture Makers",
    "description": "Custom furniture creators who use high-quality panels to construct bespoke furniture pieces that align with design trends and customer preferences.",
    "subIndustryId": 15102010,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1734630663357,
    "subIndustryName": "Construction Materials",
    "subIndustryDescription": "Manufacturers of construction materials including sand, clay, gypsum, lime, aggregates, cement, concrete and bricks. Other finished or semi-finished building materials are classified  in the Building Products Sub-Industry.",
    "industryId": 151020,
    "industryName": "Construction Materials",
    "industryGroupId": 1510,
    "industryGroupName": "Materials",
    "sectorId": 15,
    "sectorName": "Materials",
    "pageCount": 0
  },
  {
    "uuid": "7f0986bb-9ca6-4ede-8de6-a14d7d116cb7",
    "clientUuid": "feec8a1b-7498-4d2e-af12-46389ae9a095",
    "title": "Retailers of Building Supplies",
    "description": "Businesses that sell construction materials and decorative panels, looking for manufacturers to partner with for product offerings.",
    "subIndustryId": 15102010,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1734630726276,
    "subIndustryName": "Construction Materials",
    "subIndustryDescription": "Manufacturers of construction materials including sand, clay, gypsum, lime, aggregates, cement, concrete and bricks. Other finished or semi-finished building materials are classified  in the Building Products Sub-Industry.",
    "industryId": 151020,
    "industryName": "Construction Materials",
    "industryGroupId": 1510,
    "industryGroupName": "Materials",
    "sectorId": 15,
    "sectorName": "Materials",
    "pageCount": 0
  },
  {
    "uuid": "4cf2631b-48de-4bf6-9ae3-8609f83e47d1",
    "clientUuid": "feec8a1b-7498-4d2e-af12-46389ae9a095",
    "title": "Real Estate Developers",
    "description": "Developers needing bulk orders of construction materials for new housing projects and renovations, focusing on quality and design.",
    "subIndustryId": 15102010,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1734630797304,
    "subIndustryName": "Construction Materials",
    "subIndustryDescription": "Manufacturers of construction materials including sand, clay, gypsum, lime, aggregates, cement, concrete and bricks. Other finished or semi-finished building materials are classified  in the Building Products Sub-Industry.",
    "industryId": 151020,
    "industryName": "Construction Materials",
    "industryGroupId": 1510,
    "industryGroupName": "Materials",
    "sectorId": 15,
    "sectorName": "Materials",
    "pageCount": 0
  },
  {
    "uuid": "952c146c-7079-4ccf-b419-a024cbe51b37",
    "clientUuid": "feec8a1b-7498-4d2e-af12-46389ae9a095",
    "title": "Interior Decorators",
    "description": "Professional decorators who aim to select materials that bring their vision to life while considering color and texture.",
    "subIndustryId": 15102010,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1734630868893,
    "subIndustryName": "Construction Materials",
    "subIndustryDescription": "Manufacturers of construction materials including sand, clay, gypsum, lime, aggregates, cement, concrete and bricks. Other finished or semi-finished building materials are classified  in the Building Products Sub-Industry.",
    "industryId": 151020,
    "industryName": "Construction Materials",
    "industryGroupId": 1510,
    "industryGroupName": "Materials",
    "sectorId": 15,
    "sectorName": "Materials",
    "pageCount": 0
  },
  {
    "uuid": "52c7ac14-5f0d-4dec-8d8d-d38c5d8a8109",
    "clientUuid": "feec8a1b-7498-4d2e-af12-46389ae9a095",
    "title": "Hospitality Industry Stakeholders",
    "description": "Hoteliers and restaurant owners looking for durable and stylish panel solutions to enhance their interiors.",
    "subIndustryId": 15102010,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1734630933769,
    "subIndustryName": "Construction Materials",
    "subIndustryDescription": "Manufacturers of construction materials including sand, clay, gypsum, lime, aggregates, cement, concrete and bricks. Other finished or semi-finished building materials are classified  in the Building Products Sub-Industry.",
    "industryId": 151020,
    "industryName": "Construction Materials",
    "industryGroupId": 1510,
    "industryGroupName": "Materials",
    "sectorId": 15,
    "sectorName": "Materials",
    "pageCount": 0
  },
  {
    "uuid": "978f5141-411e-4da6-9640-62d8bc6310a8",
    "clientUuid": "feec8a1b-7498-4d2e-af12-46389ae9a095",
    "title": "Architectural Firms",
    "description": "Design teams that require innovative and functional paneling solutions to integrate into contemporary and traditional architectural projects.",
    "subIndustryId": 15102010,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1734631011953,
    "subIndustryName": "Construction Materials",
    "subIndustryDescription": "Manufacturers of construction materials including sand, clay, gypsum, lime, aggregates, cement, concrete and bricks. Other finished or semi-finished building materials are classified  in the Building Products Sub-Industry.",
    "industryId": 151020,
    "industryName": "Construction Materials",
    "industryGroupId": 1510,
    "industryGroupName": "Materials",
    "sectorId": 15,
    "sectorName": "Materials",
    "pageCount": 0
  },
  {
    "uuid": "f28b57eb-ae59-4844-8d90-d0de325d2aec",
    "clientUuid": "feec8a1b-7498-4d2e-af12-46389ae9a095",
    "title": "Government and Municipal Contractors",
    "description": "Entities involved in public works looking to source building materials for community and government projects.",
    "subIndustryId": 15102010,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1734631084277,
    "subIndustryName": "Construction Materials",
    "subIndustryDescription": "Manufacturers of construction materials including sand, clay, gypsum, lime, aggregates, cement, concrete and bricks. Other finished or semi-finished building materials are classified  in the Building Products Sub-Industry.",
    "industryId": 151020,
    "industryName": "Construction Materials",
    "industryGroupId": 1510,
    "industryGroupName": "Materials",
    "sectorId": 15,
    "sectorName": "Materials",
    "pageCount": 0
  },
  {
    "uuid": "014bbd86-53cd-4752-830e-0f8e5133130a",
    "clientUuid": "feec8a1b-7498-4d2e-af12-46389ae9a095",
    "title": "Construction Project Managers",
    "description": "Managers overseeing construction projects who prioritize quality materials supply and vendor reliability.",
    "subIndustryId": 15102010,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1734631165188,
    "subIndustryName": "Construction Materials",
    "subIndustryDescription": "Manufacturers of construction materials including sand, clay, gypsum, lime, aggregates, cement, concrete and bricks. Other finished or semi-finished building materials are classified  in the Building Products Sub-Industry.",
    "industryId": 151020,
    "industryName": "Construction Materials",
    "industryGroupId": 1510,
    "industryGroupName": "Materials",
    "sectorId": 15,
    "sectorName": "Materials",
    "pageCount": 0
  },
  {
    "uuid": "7edab4e6-d8cd-4e92-adef-97669457d05f",
    "clientUuid": "feec8a1b-7498-4d2e-af12-46389ae9a095",
    "title": "Green Building Advocates",
    "description": "Professionals focused on sustainable building practices needing eco-friendly panel solutions for construction.",
    "subIndustryId": 15102010,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1734631239235,
    "subIndustryName": "Construction Materials",
    "subIndustryDescription": "Manufacturers of construction materials including sand, clay, gypsum, lime, aggregates, cement, concrete and bricks. Other finished or semi-finished building materials are classified  in the Building Products Sub-Industry.",
    "industryId": 151020,
    "industryName": "Construction Materials",
    "industryGroupId": 1510,
    "industryGroupName": "Materials",
    "sectorId": 15,
    "sectorName": "Materials",
    "pageCount": 0
  },
  {
    "uuid": "d6bc8969-29a7-421d-aef0-3ae20cb90d4b",
    "clientUuid": "feec8a1b-7498-4d2e-af12-46389ae9a095",
    "title": "Office Furniture Manufacturers",
    "description": "Companies creating office furniture, in search of stylish and functional panels to enhance workspace designs.",
    "subIndustryId": 15102010,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1734631317581,
    "subIndustryName": "Construction Materials",
    "subIndustryDescription": "Manufacturers of construction materials including sand, clay, gypsum, lime, aggregates, cement, concrete and bricks. Other finished or semi-finished building materials are classified  in the Building Products Sub-Industry.",
    "industryId": 151020,
    "industryName": "Construction Materials",
    "industryGroupId": 1510,
    "industryGroupName": "Materials",
    "sectorId": 15,
    "sectorName": "Materials",
    "pageCount": 0
  },
  {
    "uuid": "dd6d0db4-f88c-4485-87fb-57d2aedb1c9f",
    "clientUuid": "feec8a1b-7498-4d2e-af12-46389ae9a095",
    "title": "Remodeling Contractors",
    "description": "Specialized contractors who focus on renovating spaces and require various decorative panels for their projects.",
    "subIndustryId": 15102010,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1734631384680,
    "subIndustryName": "Construction Materials",
    "subIndustryDescription": "Manufacturers of construction materials including sand, clay, gypsum, lime, aggregates, cement, concrete and bricks. Other finished or semi-finished building materials are classified  in the Building Products Sub-Industry.",
    "industryId": 151020,
    "industryName": "Construction Materials",
    "industryGroupId": 1510,
    "industryGroupName": "Materials",
    "sectorId": 15,
    "sectorName": "Materials",
    "pageCount": 0
  }
]
export default audience