const audience = [
  {
    "uuid": "f63cc9d5-58c2-46b5-903e-f0617c02b667",
    "clientUuid": "9fef1972-4a91-4605-bfd4-7e76638440e7",
    "title": "Manufacturers outsourcing metal cutting",
    "description": "Manufacturers outsourcing the metal cutting process of their assembly lines. Their over reliance on external vendors slows down their production processes from vendor delay. It also increases their costs and reduces their profit margins while reducing their contract opportunity.\nThey require efficient, in-house metal cutting solutions, such as Laser CNC Cutting Machines, to minimize delays, improve cost control, and capture more business opportunities by scaling production to meet demand.\n\nOur ideal customer personas is looking to solves the following challenges:\nHigh Production Delays: Manufacturers outsourcing metal cutting experience significant delays as the reliance on external vendors extends lead times and disrupts their production schedules, slowing down their overall manufacturing process.\nSmall Profit Margin: Manufacturers outsourcing metal cutting face reduced profit margins because the involvement of numerous intermediary companies in the process increases costs, cutting into their profits.\nRevenue loss from missed opportunities: Manufacturers outsourcing metal cutting encounter revenue loss when they are unable to meet high demand due to limited in-house capacity, leading to missed opportunities and reduced business growth.\n\n",
    "subIndustryId": 20102010,
    "countryId": 11,
    "stateId": 3651,
    "cityId": 873,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1733921765930,
    "subIndustryName": "Building Products",
    "subIndustryDescription": "Manufacturers of building components and home improvement products and equipment. Excludes lumber and plywood classified under Forest Products and cement and other materials classified in the Construction Materials Sub-Industry.",
    "industryId": 201020,
    "industryName": "Building Products",
    "industryGroupId": 2010,
    "industryGroupName": "Capital Goods",
    "sectorId": 20,
    "sectorName": "Industrials",
    "countryName": "Argentina",
    "stateName": "Chubut",
    "cityName": "Departamento de Cushamen",
    "pageCount": 35
  },
  {
    "uuid": "fb2dc5ce-e304-466b-84cd-bda5ad2537d5",
    "clientUuid": "9fef1972-4a91-4605-bfd4-7e76638440e7",
    "title": "Metal Fabrication Shops",
    "description": "Businesses specializing in the custom fabrication of metal parts and structures require advanced laser cutting systems to improve precision and efficiency.",
    "subIndustryId": 20102010,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1734643101803,
    "subIndustryName": "Building Products",
    "subIndustryDescription": "Manufacturers of building components and home improvement products and equipment. Excludes lumber and plywood classified under Forest Products and cement and other materials classified in the Construction Materials Sub-Industry.",
    "industryId": 201020,
    "industryName": "Building Products",
    "industryGroupId": 2010,
    "industryGroupName": "Capital Goods",
    "sectorId": 20,
    "sectorName": "Industrials",
    "pageCount": 0
  },
  {
    "uuid": "1bf5f3c8-b965-41b2-a345-250f2d032cd0",
    "clientUuid": "9fef1972-4a91-4605-bfd4-7e76638440e7",
    "title": "Manufacturers of Heavy Equipment",
    "description": "Companies manufacturing heavy machinery and equipment that need high-quality metal components for assembly utilize cutting-edge metal processing technologies.",
    "subIndustryId": 20102010,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1734643170693,
    "subIndustryName": "Building Products",
    "subIndustryDescription": "Manufacturers of building components and home improvement products and equipment. Excludes lumber and plywood classified under Forest Products and cement and other materials classified in the Construction Materials Sub-Industry.",
    "industryId": 201020,
    "industryName": "Building Products",
    "industryGroupId": 2010,
    "industryGroupName": "Capital Goods",
    "sectorId": 20,
    "sectorName": "Industrials",
    "pageCount": 0
  },
  {
    "uuid": "543db69a-b747-4c4a-8f58-1e945ea4a8b6",
    "clientUuid": "9fef1972-4a91-4605-bfd4-7e76638440e7",
    "title": "Automotive Parts Manufacturers",
    "description": "Firms producing automotive components requiring precise metal cutting and bending solutions to ensure product quality and performance standards.",
    "subIndustryId": 20102010,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1734643249853,
    "subIndustryName": "Building Products",
    "subIndustryDescription": "Manufacturers of building components and home improvement products and equipment. Excludes lumber and plywood classified under Forest Products and cement and other materials classified in the Construction Materials Sub-Industry.",
    "industryId": 201020,
    "industryName": "Building Products",
    "industryGroupId": 2010,
    "industryGroupName": "Capital Goods",
    "sectorId": 20,
    "sectorName": "Industrials",
    "pageCount": 0
  },
  {
    "uuid": "940e7936-47d4-47c1-9706-6749876e9aff",
    "clientUuid": "9fef1972-4a91-4605-bfd4-7e76638440e7",
    "title": "Aerospace Component Manufacturers",
    "description": "Manufacturers in the aerospace sector that produce lightweight and high-strength components requiring enhanced metal processing capabilities.",
    "subIndustryId": 20101010,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1734643318281,
    "subIndustryName": "Aerospace & Defense",
    "subIndustryDescription": "Manufacturers of civil or military aerospace and defense equipment, parts or products. Includes defense electronics and space equipment.",
    "industryId": 201010,
    "industryName": "Aerospace & Defense",
    "industryGroupId": 2010,
    "industryGroupName": "Capital Goods",
    "sectorId": 20,
    "sectorName": "Industrials",
    "pageCount": 0
  },
  {
    "uuid": "03890db6-f2c0-45f7-95ef-02759a0167a7",
    "clientUuid": "9fef1972-4a91-4605-bfd4-7e76638440e7",
    "title": "Construction Firms",
    "description": "Companies involved in construction projects that require robust metal components and efficient processing solutions for building structures.",
    "subIndustryId": 20102010,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1734643376477,
    "subIndustryName": "Building Products",
    "subIndustryDescription": "Manufacturers of building components and home improvement products and equipment. Excludes lumber and plywood classified under Forest Products and cement and other materials classified in the Construction Materials Sub-Industry.",
    "industryId": 201020,
    "industryName": "Building Products",
    "industryGroupId": 2010,
    "industryGroupName": "Capital Goods",
    "sectorId": 20,
    "sectorName": "Industrials",
    "pageCount": 0
  },
  {
    "uuid": "a22ef775-3298-449d-a835-cd1ef69f53c5",
    "clientUuid": "9fef1972-4a91-4605-bfd4-7e76638440e7",
    "title": "Metal Recycling Facilities",
    "description": "Facilities that process scrap metal and require efficient cutting and bending machines to prepare materials for resale or reuse.",
    "subIndustryId": 20102010,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1734643458510,
    "subIndustryName": "Building Products",
    "subIndustryDescription": "Manufacturers of building components and home improvement products and equipment. Excludes lumber and plywood classified under Forest Products and cement and other materials classified in the Construction Materials Sub-Industry.",
    "industryId": 201020,
    "industryName": "Building Products",
    "industryGroupId": 2010,
    "industryGroupName": "Capital Goods",
    "sectorId": 20,
    "sectorName": "Industrials",
    "pageCount": 0
  },
  {
    "uuid": "611bd3b6-593a-4f99-afe3-0007a3387cee",
    "clientUuid": "9fef1972-4a91-4605-bfd4-7e76638440e7",
    "title": "Artisans and Metal Artists",
    "description": "Professional artists or artisans who require specialized equipment for intricate metalwork and sculpture production using laser technology.",
    "subIndustryId": 20102010,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1734643547894,
    "subIndustryName": "Building Products",
    "subIndustryDescription": "Manufacturers of building components and home improvement products and equipment. Excludes lumber and plywood classified under Forest Products and cement and other materials classified in the Construction Materials Sub-Industry.",
    "industryId": 201020,
    "industryName": "Building Products",
    "industryGroupId": 2010,
    "industryGroupName": "Capital Goods",
    "sectorId": 20,
    "sectorName": "Industrials",
    "pageCount": 0
  },
  {
    "uuid": "0e5434b9-a54d-4b0b-9d22-995bf1c42e39",
    "clientUuid": "9fef1972-4a91-4605-bfd4-7e76638440e7",
    "title": "Sheet Metal Workers",
    "description": "Skilled tradespeople specializing in the installation and fabrication of sheet metal who benefit from advanced cutting and shaping machines.",
    "subIndustryId": 20102010,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1734643622509,
    "subIndustryName": "Building Products",
    "subIndustryDescription": "Manufacturers of building components and home improvement products and equipment. Excludes lumber and plywood classified under Forest Products and cement and other materials classified in the Construction Materials Sub-Industry.",
    "industryId": 201020,
    "industryName": "Building Products",
    "industryGroupId": 2010,
    "industryGroupName": "Capital Goods",
    "sectorId": 20,
    "sectorName": "Industrials",
    "pageCount": 0
  },
  {
    "uuid": "8f0cf301-fac1-41d1-b20a-961c87b40003",
    "clientUuid": "9fef1972-4a91-4605-bfd4-7e76638440e7",
    "title": "HVAC System Manufacturers",
    "description": "Manufacturers of heating, ventilation, and air conditioning systems that require precise sheet metal for ductwork and fittings.",
    "subIndustryId": 20102010,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1734643690147,
    "subIndustryName": "Building Products",
    "subIndustryDescription": "Manufacturers of building components and home improvement products and equipment. Excludes lumber and plywood classified under Forest Products and cement and other materials classified in the Construction Materials Sub-Industry.",
    "industryId": 201020,
    "industryName": "Building Products",
    "industryGroupId": 2010,
    "industryGroupName": "Capital Goods",
    "sectorId": 20,
    "sectorName": "Industrials",
    "pageCount": 0
  },
  {
    "uuid": "021c340f-902f-4eb0-965c-a85705a75903",
    "clientUuid": "9fef1972-4a91-4605-bfd4-7e76638440e7",
    "title": "Research and Development Labs",
    "description": "R&D facilities that need precision cutting and bending machines for experimental metalworking projects and prototype development.",
    "subIndustryId": 20102010,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1734643765517,
    "subIndustryName": "Building Products",
    "subIndustryDescription": "Manufacturers of building components and home improvement products and equipment. Excludes lumber and plywood classified under Forest Products and cement and other materials classified in the Construction Materials Sub-Industry.",
    "industryId": 201020,
    "industryName": "Building Products",
    "industryGroupId": 2010,
    "industryGroupName": "Capital Goods",
    "sectorId": 20,
    "sectorName": "Industrials",
    "pageCount": 0
  },
  {
    "uuid": "e624a9ec-72f5-4190-a65e-d509a43f02b3",
    "clientUuid": "9fef1972-4a91-4605-bfd4-7e76638440e7",
    "title": "Educational Institutions and Technical Schools",
    "description": "Vocational schools and colleges that provide training in metalworking and welding, needing reliable and high-quality machines for hands-on learning.",
    "subIndustryId": 20102010,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1734643849194,
    "subIndustryName": "Building Products",
    "subIndustryDescription": "Manufacturers of building components and home improvement products and equipment. Excludes lumber and plywood classified under Forest Products and cement and other materials classified in the Construction Materials Sub-Industry.",
    "industryId": 201020,
    "industryName": "Building Products",
    "industryGroupId": 2010,
    "industryGroupName": "Capital Goods",
    "sectorId": 20,
    "sectorName": "Industrials",
    "pageCount": 0
  },
  {
    "uuid": "973ad470-ba53-4ce3-a15f-48b6f2955e16",
    "clientUuid": "9fef1972-4a91-4605-bfd4-7e76638440e7",
    "title": "Construction Material Suppliers",
    "description": "Suppliers of construction materials who require fabrication services and metal processing machines to support their supply chains.",
    "subIndustryId": 20102010,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1734643923941,
    "subIndustryName": "Building Products",
    "subIndustryDescription": "Manufacturers of building components and home improvement products and equipment. Excludes lumber and plywood classified under Forest Products and cement and other materials classified in the Construction Materials Sub-Industry.",
    "industryId": 201020,
    "industryName": "Building Products",
    "industryGroupId": 2010,
    "industryGroupName": "Capital Goods",
    "sectorId": 20,
    "sectorName": "Industrials",
    "pageCount": 0
  },
  {
    "uuid": "209d0380-11e0-4dce-a858-8790fca4917b",
    "clientUuid": "9fef1972-4a91-4605-bfd4-7e76638440e7",
    "title": "Solar Power Equipment Manufacturers",
    "description": "Companies involved in the production of solar panels and solar energy systems requiring precise metal components for assembly.",
    "subIndustryId": 20102010,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1734643993400,
    "subIndustryName": "Building Products",
    "subIndustryDescription": "Manufacturers of building components and home improvement products and equipment. Excludes lumber and plywood classified under Forest Products and cement and other materials classified in the Construction Materials Sub-Industry.",
    "industryId": 201020,
    "industryName": "Building Products",
    "industryGroupId": 2010,
    "industryGroupName": "Capital Goods",
    "sectorId": 20,
    "sectorName": "Industrials",
    "pageCount": 0
  },
  {
    "uuid": "47b89e2b-fd10-40f5-a66a-d90fcb6a8680",
    "clientUuid": "9fef1972-4a91-4605-bfd4-7e76638440e7",
    "title": "Furniture Manufacturers",
    "description": "Companies producing metal and mixed-material furnishings that require innovative cutting solutions for design and durability.",
    "subIndustryId": 20102010,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1734644071148,
    "subIndustryName": "Building Products",
    "subIndustryDescription": "Manufacturers of building components and home improvement products and equipment. Excludes lumber and plywood classified under Forest Products and cement and other materials classified in the Construction Materials Sub-Industry.",
    "industryId": 201020,
    "industryName": "Building Products",
    "industryGroupId": 2010,
    "industryGroupName": "Capital Goods",
    "sectorId": 20,
    "sectorName": "Industrials",
    "pageCount": 0
  },
  {
    "uuid": "c4fe544a-f358-4832-aa4d-712809373c65",
    "clientUuid": "9fef1972-4a91-4605-bfd4-7e76638440e7",
    "title": "Medical Device Manufacturers",
    "description": "Manufacturers of medical devices needing precise metal working for components such as frames, casings, and structural elements.",
    "subIndustryId": 35101010,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1734644137868,
    "subIndustryName": "Health Care Equipment",
    "subIndustryDescription": "Manufacturers of health care equipment and devices. Includes medical instruments, drug delivery systems, cardiovascular & orthopedic devices, and diagnostic equipment.",
    "industryId": 351010,
    "industryName": "Health Care Equipment & Supplies",
    "industryGroupId": 3510,
    "industryGroupName": "Health Care Equipment & Services",
    "sectorId": 35,
    "sectorName": "Health Care",
    "pageCount": 0
  },
  {
    "uuid": "a2a08ecb-2680-476d-bf4c-2f10b324fbc9",
    "clientUuid": "9fef1972-4a91-4605-bfd4-7e76638440e7",
    "title": "Oil and Gas Industry Suppliers",
    "description": "Firms supplying equipment and components to the oil and gas industry that require heavy-duty metal cutting and processing machinery.",
    "subIndustryId": 10102040,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1734644204507,
    "subIndustryName": "Oil & Gas Storage & Transportation",
    "subIndustryDescription": "Companies engaged in the storage and/or transportation of oil, gas and/or refined products. Includes diversified midstream natural gas companies, oil and refined product pipelines, coal slurry pipelines and oil & gas shipping companies.",
    "industryId": 101020,
    "industryName": "Oil, Gas & Consumable Fuels",
    "industryGroupId": 1010,
    "industryGroupName": "Energy",
    "sectorId": 10,
    "sectorName": "Energy",
    "pageCount": 0
  },
  {
    "uuid": "dff9f164-b43c-4983-aa69-6675e5b8d9e3",
    "clientUuid": "9fef1972-4a91-4605-bfd4-7e76638440e7",
    "title": "Signage and Display Manufacturers",
    "description": "Businesses creating custom signs and displays that need cutting and engraving machines to manufacture high-quality products.",
    "subIndustryId": 20102010,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1734644286580,
    "subIndustryName": "Building Products",
    "subIndustryDescription": "Manufacturers of building components and home improvement products and equipment. Excludes lumber and plywood classified under Forest Products and cement and other materials classified in the Construction Materials Sub-Industry.",
    "industryId": 201020,
    "industryName": "Building Products",
    "industryGroupId": 2010,
    "industryGroupName": "Capital Goods",
    "sectorId": 20,
    "sectorName": "Industrials",
    "pageCount": 0
  },
  {
    "uuid": "5a3650b6-4292-4299-82f6-9a8a5d2971c3",
    "clientUuid": "9fef1972-4a91-4605-bfd4-7e76638440e7",
    "title": "Food Processing Equipment Manufacturers",
    "description": "Manufacturers producing machinery for the food industry, needing reliable metal components that meet hygiene and serviceability standards.",
    "subIndustryId": 20102010,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1734644352454,
    "subIndustryName": "Building Products",
    "subIndustryDescription": "Manufacturers of building components and home improvement products and equipment. Excludes lumber and plywood classified under Forest Products and cement and other materials classified in the Construction Materials Sub-Industry.",
    "industryId": 201020,
    "industryName": "Building Products",
    "industryGroupId": 2010,
    "industryGroupName": "Capital Goods",
    "sectorId": 20,
    "sectorName": "Industrials",
    "pageCount": 0
  },
  {
    "uuid": "15ee5861-a47b-4f83-a5a2-63de697f53ac",
    "clientUuid": "9fef1972-4a91-4605-bfd4-7e76638440e7",
    "title": "General Manufacturers with In-House Processing Needs",
    "description": "Various manufacturers looking to reduce outsourcing costs and improve production speed through in-house metal processing capabilities.",
    "subIndustryId": 20102010,
    "countryId": null,
    "stateId": null,
    "cityId": null,
    "revenue": null,
    "image": null,
    "score": null,
    "createdAt": 1734644423707,
    "subIndustryName": "Building Products",
    "subIndustryDescription": "Manufacturers of building components and home improvement products and equipment. Excludes lumber and plywood classified under Forest Products and cement and other materials classified in the Construction Materials Sub-Industry.",
    "industryId": 201020,
    "industryName": "Building Products",
    "industryGroupId": 2010,
    "industryGroupName": "Capital Goods",
    "sectorId": 20,
    "sectorName": "Industrials",
    "pageCount": 0
  }
]
export default audience